### ISSUE TITLE
add a script to find dead links

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/RequestPolicyContinued.github.io#10]
I think there are two types of dead links
- 404 errors
- non-existing anchors, e.g. `index.html#non-existing-anchor`

**Comment by DJ-Leith** [comment]
Yes, a script would be useful.

In my reading I have noticed the following:

Quoted from #14

> I have now read all of the **website** https://requestpolicycontinued.github.io/
> and all of the **wiki** https://github.com/RequestPolicyContinued/requestpolicy/wiki

**_1.**_ **wiki** - Nearly all the links in the wiki are working, I have mainly noticed 'broken links' on the website.

**_2.**_ **website** - Links to external sites (e.g. to AMO or to wikipedia) are working.

**_3.**_ Some pages are 'unreachable'; they might not exist.
The **wiki** has Navigation (#17), using the frame on the top right, to 13 pages (as at 2015-07-02).
The **website** can only link via links **in the pages**.
I am using "unreachable" to mean a page with no link to it.
For example, AFAIK, there is no link to "What-is-prefetching".

I expect the link to be: 
https://requestpolicycontinued.github.io/What-is-prefetching.html
The page does exist - good.

Another unreachable page, that does exist, is: 
https://requestpolicycontinued.github.io/Risk-of-trusting-subdomains.html

**_4.**_ Some pages are (were) 404.
The link from the Home page to the About page was fixed by @myrdd
https://github.com/RequestPolicyContinued/requestpolicy/wiki/Home/_history

**_5.**_ **Anchors**

If, like me, you are using NoScript, you have to enable NoScript to allow JavaScript to run on the **wiki** and/or the **website** in order to test/use the anchors.

Example
https://requestpolicycontinued.github.io/FAQ.html

Has several topics: these are anchor links are like this:

https://requestpolicycontinued.github.io/FAQ.html#how-to-deal-with-ajaxgoogleapiscom

The <code>FAQ.html</code> page does not contain the 'anchor to land on'. 

Question 1: in the **website** html are there **any** anchors to land on?

Question 2: are the anchors generated when the 'wiki is pushed to the website'?

A broken anchor in the **wiki** is

https://github.com/RequestPolicyContinued/requestpolicy/wiki

> ... either manually, or by subscribing to premade policies (subscriptions) maintained by others ...

The link in "(subscriptions)" is to
https://github.com/RequestPolicyContinued/requestpolicy/wiki#Setting-up---subscriptions

This also does not work in the website (where the link is to):
https://requestpolicycontinued.github.io/#Setting-up---subscriptions

**_6.**_ Related topic, I noticed that

<code>about:requestpolicy?yourpolicy</code> has a link called "About".
This attempts to go to 
https://requestpolicycontinued.github.io/#about
You end up at the main page of the **website**.

I speculate that the intended destination might be:
https://requestpolicycontinued.github.io/About.html

**Comment by myrdd** [comment]
@DJ-Leith I don't think we should look for "unreachable" links on the website, only dead links.

> https://requestpolicycontinued.github.io/FAQ.html#how-to-deal-with-ajaxgoogleapiscom

Correct. That anchor does not exist. Therefore I mentioned "anchors" in the first post.
The correct anchor is [`how-to-deal-with-ajax.googleapis.com`](https://requestpolicycontinued.github.io/FAQ.html#how-to-deal-with-ajax.googleapis.com).

> **6.** Related topic

Thanks for that hint. See https://github.com/RequestPolicyContinued/requestpolicy/issues/682.
